### ISSUE TITLE
MouthRight/Left Logic

### ISSUE THREAD

**Issue by hantnor** [Adjerry91/VRCFaceTracking-Templates#14]
(Unified Expressions) Debug menu lists MouthRight and MouthLeft, but corresponding animations have been changed to the split MouthUpper/LowerRight/Left.

Avatars that do not have this split will render unusable. Possibly leave it combined?

**Comment by Adjerry91** [comment]
I am not sure what you are referring to because all the MouthLeft and MouthRight are not split

**Comment by hantnor** [comment]
![image](https://github.com/user-attachments/assets/7952f7b9-1088-4a90-8168-8eafdaff6698)
It seems to have been resolved in v6.3.3, but was present in the previous version.
