### ISSUE TITLE
[v6.4.x] Request to make "Disable Gestures" toggle only disable facial expressions, not gestures.

### ISSUE THREAD

**Issue by xNanochip** [Adjerry91/VRCFaceTracking-Templates#16]
In v6.4.x, a Disable Gestures toggle was created which has the same effect as disabling gestures through the default vrc setting. This causes issues for people that want to have face tracking with disabled facial expressions while still being able to interact with different avatar systems and/or props on their avatars that require gestures. As currently, they cannot interact with their avatar props while the Disable Gestures toggle is on.

In previous versions, you had people create a facial expressions toggle which seems to now have been replaced with this Disable Gestures toggle. I hope a better solution can be made to have a similar effect as the previous way of doing it, else I think this change should be reverted, as it seems to be no different than the default vrc gestures setting and is a duplicate.

For example, in one of my props I have recently released, you have to grab the prop from your hip using Gestures. I have replicated and verified this issued with two other people who have also encountered this problem.

**Comment by Adjerry91** [comment]
Unpack the prefab and remove the Gesture Disable sub object.

**Comment by Adjerry91** [comment]
Changed the Disable Gesture Expressions to Disable Facial Expressions. Remove the Gesture Disable VRCFury toggle prefab. v6.4.2
