### ISSUE TITLE
What dependencies require unity 2022?

### ISSUE THREAD

**Issue by deadcxap** [Adjerry91/VRCFaceTracking-Templates#8]
Due to the use of other scripts on my avatar, I cannot upgrade to the 2022 version of unity. Tell me what exactly in the latest versions of your template requires changing the version? I searched for commits and saw a strange entry that “vrcfurry v3 is required for update”... But this version of vrcfurry is not on their website or in their repositories, the latest version is 1.754.0.

**Comment by Adjerry91** [comment]
Prefabs are made on 2022 on v5.2.0+
